spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fyp-grading

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

    notification:
      queue: "notification-queue"
      exchange: "notification-exchange"
      routing-key: "notification-key"

    retry-notification:
      queue: "retry-notification-queue"
      exchange: "retry-notification-exchange"
      routing-key: "retry-notification-key"
      ttl: 2000
      max-count: 3

    grades:
      queue: "grades-queue"
      exchange: "grades-exchange"
      routing-key: "grades-key"

    retry-grades:
      queue: "retry-notification-queue"
      exchange: "retry-notification-exchange"
      routing-key: "retry-notification-key"
      ttl: 2000
      max-count: 3

    dead-letter:
      queue: "dead-queue"
      exchange: "dead-exchange"
      routing-key: "dead-key"