logging:
  level:
    root: INFO

spring:
  data:
    mongodb:
      uri: ${DATABASE_URL}

#eureka:
#  client:
#    service-url:
#      default-zone: ${REGISTRY_SERVICE_URL}
#    healthcheck:
#      enabled: true
#  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1

server:
  port: ${PORT}