build:
  version: ${BUILD_VERSION}

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: "FYP Grading project - Evaluation Microservice"
    version: ${BUILD_VERSION}

logging:
  level:
    root: INFO

management:
  metrics:
    tags:
      application: ${SPRING_APPLICATION_NAME}

services:
  admin-service-name: ${ADMIN_SERVICE_NAME}
  rubric-service-name: ${RUBRIC_SERVICE_NAME}

spring:
  data:
    mongodb:
      uri: ${DATABASE_URL}

  # this will in fact not be used as the service will register with eureka
  # and get its configuration from the config server dynamically in the bootstrap phase (bootstrap.yml)
  config:
    import: "optional:configserver:"

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${PORT}